# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  app:
    image: node:22
    volumes:
      - ./:/code
    working_dir: /code
    command: sh -c "test -d node_modules || npm install; npm run start"
    ports:
      - "${APP_PORT:-8998}:8998"
    tty: true
